package com.example.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.QuantTheme
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Lightbulb
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.filled.Info

@Composable
fun MarketSuggestionsView(
    uiState: TradeUiState,
    onGenerate: () -> Unit
) {
    Column(modifier = Modifier.fillMaxSize().padding(16.dp)) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Column(modifier = Modifier.weight(1f)) {
                Text("AI Market Ideas", fontSize = 24.sp, fontWeight = FontWeight.Bold, color = QuantTheme.textPrimary)
                Text("Generated by trending news & X signals", fontSize = 14.sp, color = QuantTheme.textMuted)
            }
            Button(
                onClick = onGenerate,
                enabled = !uiState.isGeneratingSuggestions,
                colors = ButtonDefaults.buttonColors(containerColor = QuantTheme.accentBlue)
            ) {
                if (uiState.isGeneratingSuggestions) {
                    CircularProgressIndicator(color = Color.White, modifier = Modifier.size(20.dp), strokeWidth = 2.dp)
                } else {
                    Icon(Icons.Default.AutoAwesome, contentDescription = "Generate", modifier = Modifier.size(20.dp))
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("Generate")
                }
            }
        }
        
        Spacer(modifier = Modifier.height(16.dp))
        
        // Explain Polymarket Address if requested
        Card(
            colors = CardDefaults.cardColors(containerColor = QuantTheme.surface),
            shape = RoundedCornerShape(12.dp),
            modifier = Modifier.fillMaxWidth()
        ) {
            Column(modifier = Modifier.padding(16.dp)) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Icon(Icons.Default.Info, contentDescription = "Info", tint = QuantTheme.accentBlue, modifier = Modifier.size(20.dp))
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("What is the Polymarket Address?", color = QuantTheme.textPrimary, fontWeight = FontWeight.Bold, fontSize = 16.sp)
                }
                Spacer(modifier = Modifier.height(8.dp))
                Text("The Polymarket Address (POLY_ADDRESS) is your Polygon signer address or funder wallet. It is used in L1/L2 authentication when trading via the CLOB API. The funder address holds your USDC and MATIC funds for placing limit orders, which are validated through ERC-1271 (deposit wallet flow for new API users).", 
                    color = QuantTheme.textBody, fontSize = 14.sp, lineHeight = 20.sp)
            }
        }
        
        Spacer(modifier = Modifier.height(16.dp))

        if (uiState.marketSuggestions.isEmpty()) {
            Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    Icon(Icons.Default.Lightbulb, contentDescription = "Empty", tint = QuantTheme.textMuted, modifier = Modifier.size(64.dp))
                    Spacer(modifier = Modifier.height(16.dp))
                    Text("No ideas generated yet.", color = QuantTheme.textMuted, fontSize = 16.sp)
                }
            }
        } else {
            LazyColumn(
                modifier = Modifier.fillMaxSize(),
                contentPadding = PaddingValues(bottom = 80.dp),
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                items(uiState.marketSuggestions) { suggestion ->
                    SuggestionCard(suggestion)
                }
            }
        }
    }
}

@Composable
fun SuggestionCard(suggestion: MarketSuggestion) {
    Card(
        colors = CardDefaults.cardColors(containerColor = QuantTheme.surface),
        shape = RoundedCornerShape(12.dp),
        modifier = Modifier.fillMaxWidth()
    ) {
        Column(modifier = Modifier.padding(16.dp)) {
            Text(suggestion.title, color = QuantTheme.textPrimary, fontSize = 18.sp, fontWeight = FontWeight.Bold)
            Spacer(modifier = Modifier.height(8.dp))
            
            Row(verticalAlignment = Alignment.CenterVertically) {
                Text("Confidence: ${(suggestion.confidence * 100).toInt()}%", color = QuantTheme.accentGreen, fontSize = 14.sp, fontWeight = FontWeight.Bold)
                Spacer(modifier = Modifier.width(16.dp))
                Text("Source: ${suggestion.resolutionSource}", color = QuantTheme.textMuted, fontSize = 12.sp)
            }
            
            Spacer(modifier = Modifier.height(12.dp))
            Text(suggestion.rationale, color = QuantTheme.textBody, fontSize = 14.sp)
            
            Spacer(modifier = Modifier.height(12.dp))
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                suggestion.tags.forEach { tag ->
                    Box(
                        modifier = Modifier
                            .background(QuantTheme.background, RoundedCornerShape(4.dp))
                            .padding(horizontal = 8.dp, vertical = 4.dp)
                    ) {
                        Text("#$tag", color = QuantTheme.accentBlue, fontSize = 12.sp, fontWeight = FontWeight.Bold)
                    }
                }
            }
        }
    }
}
